/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acosold;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Radouan
 */
public class AcoSold extends javax.swing.JFrame {
    
    

    /**
     * Creates new form AcoSold
     */
   
        Calendar calendar = Calendar.getInstance();
        int dayOfMonth = calendar.get(Calendar.DAY_OF_MONTH);
       
    
    Date today = new Date();                                                     // creatting an instance of date named today
    
    Alimentation alim = new Alimentation();
    Client clt = new Client();
    Double sNowAfterAddition = 0.0;
    
    // the begining of Constractor
    public AcoSold() {
        initComponents();
        Date d = new Date();
        jDateChooser_Alim.setDate(d);
        jDateChooser_DateInt.setDate(d);
     this.setIconImage(new ImageIcon(getClass().getResource("acoLogo.jpg")).getImage());
        
       // choose a format
       
       DateFormat df = DateFormat.getInstance();                                 // create an instance of date
       String srgDate = df.format(today);                                        // getting current date and putting it in a string named srgDate
       jLabel_Date.setText(srgDate);                                             // displaying date and time on a jlable called jLabel_Date
       alim.fillComboBox();                                                      // putting technican names on a combobox for intervention
       clt.fillClientComboBox();
       alim.fillComboBoxSolder();                                                // putting technician names on a combobox for giving money
       alim.fillTableAlim(jTable_Alim);                                          // filling the table that hold alimentation
       alim.fillTableFrais(jTable_Frais);                                        // filling table that holds dispences
       
       jTextField_SoldNow.setText(String.valueOf(alim.totalAlim()));
       
       
       jTextField_NewSold.setText(String.valueOf(alim.moneyLeft()));             // putting the total of alim in text field named jTextField_SoldNow
//       System.out.println("test");
//       System.out.println(alim.moneyLeft());

         
        jButton_AddToSoldNow.setEnabled(false);
       
                                                                                 // getting the money left after sub intervention money from alim total and putting the result in textfield named jTextfield_NewSold
       
       if(!jCheckBox_Confirm.isSelected())                                       // this line check if check box is checked
       {
          jComboBox_FullNameTech.setEnabled(false);                              // if false, the jComboBox_FullNameTech will be disable
          jTextField_TotalFrais.setEnabled(false);                               // if false, the jTextField_TotalFrais will be disable
          jButton_Solder.setEnabled(false);                                      // if false, the jButton_Solder will be disable
       }
       
       //it grabe last month money and put it in the top right corner of gui
        alim.grabLastMonthMoney();
        
        //calculate the total of alim + last month (+ and -)
        if(jCheckBox_Calculate.isSelected())
        {
            Double lastMonth = Double.valueOf(jTextField_LastMonth.getText());
            Double soldNow = Double.valueOf(jTextField_SoldNow.getText());
            Double zammel = lastMonth + soldNow;
            
            jTextField_SoldNow.setText(String.valueOf(zammel));
        }// calculation ends here
        
        //put the money total in a jLable_TotalFrais to be displayed at the start of the app
            jLabel_TotalFrais.setText(String.valueOf(alim.totalFrais()));
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
            
       
       
    }// the end of the constractor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_LastMonth = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_AlimSold = new javax.swing.JTextField();
        jDateChooser_Alim = new com.toedter.calendar.JDateChooser();
        jButton_Valider = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField_SoldNow = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_FullName = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser_DateInt = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Frais = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_MotifInt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Frais = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_FullNameTech = new javax.swing.JComboBox<>();
        jCheckBox_Confirm = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Alim = new javax.swing.JTable();
        jTextField_Motif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_TotalFrais = new javax.swing.JTextField();
        jButton_Solder = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_NewSold = new javax.swing.JTextField();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Bonjours = new javax.swing.JLabel();
        jButton_ValiderDeplacement = new javax.swing.JButton();
        jButton_AddToSoldNow = new javax.swing.JButton();
        jCheckBox_Calculate = new javax.swing.JCheckBox();
        jButton_SupprimerLigne = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_TotalFrais = new javax.swing.JLabel();
        jLabel_Differance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox_Client = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton_Refrech = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcoSold v1.3");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_LastMonth.setEditable(false);
        jTextField_LastMonth.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jTextField_LastMonth.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_LastMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_LastMonth.setText("0.0");
        jTextField_LastMonth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_LastMonth.setCaretColor(new java.awt.Color(102, 102, 0));
        jTextField_LastMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LastMonthMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Le reste du dernier mois:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alim:");

        jTextField_AlimSold.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jTextField_AlimSold.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_AlimSold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_AlimSold.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_AlimSold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_AlimSoldMouseClicked(evt);
            }
        });
        jTextField_AlimSold.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AlimSoldKeyTyped(evt);
            }
        });

        jDateChooser_Alim.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser_Alim.setForeground(new java.awt.Color(0, 102, 102));
        jDateChooser_Alim.setToolTipText("");
        jDateChooser_Alim.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N

        jButton_Valider.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_Valider.setForeground(new java.awt.Color(102, 102, 102));
        jButton_Valider.setText("Valider");
        jButton_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValiderActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));

        jTextField_SoldNow.setEditable(false);
        jTextField_SoldNow.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_SoldNow.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jTextField_SoldNow.setForeground(new java.awt.Color(0, 153, 0));
        jTextField_SoldNow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_SoldNow.setText("0.0");
        jTextField_SoldNow.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("SOLD mois actuale :");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nom de technicien:");

        jComboBox_FullName.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jComboBox_FullName.setForeground(new java.awt.Color(102, 102, 102));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Client:");

        jDateChooser_DateInt.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser_DateInt.setForeground(new java.awt.Color(0, 102, 102));
        jDateChooser_DateInt.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Date d'intervention:");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Frais divers:");

        jTextField_Frais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FraisKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Motif:");

        jTextArea_MotifInt.setColumns(20);
        jTextArea_MotifInt.setLineWrap(true);
        jTextArea_MotifInt.setRows(8);
        jScrollPane1.setViewportView(jTextArea_MotifInt);

        jTable_Frais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ID", "     Nom Technicien", "      Nom de Client", "          Date ", "          Frais", "                                                      Motif de Deplacement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Frais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_FraisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Frais);
        if (jTable_Frais.getColumnModel().getColumnCount() > 0) {
            jTable_Frais.getColumnModel().getColumn(0).setMinWidth(30);
            jTable_Frais.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Frais.getColumnModel().getColumn(0).setMaxWidth(90);
            jTable_Frais.getColumnModel().getColumn(1).setMinWidth(120);
            jTable_Frais.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable_Frais.getColumnModel().getColumn(1).setMaxWidth(160);
            jTable_Frais.getColumnModel().getColumn(2).setMinWidth(120);
            jTable_Frais.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable_Frais.getColumnModel().getColumn(2).setMaxWidth(500);
            jTable_Frais.getColumnModel().getColumn(3).setMinWidth(100);
            jTable_Frais.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_Frais.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable_Frais.getColumnModel().getColumn(4).setMinWidth(100);
            jTable_Frais.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_Frais.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Nom de technicien:");

        jComboBox_FullNameTech.setBackground(new java.awt.Color(255, 248, 153));
        jComboBox_FullNameTech.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jComboBox_FullNameTech.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox_FullNameTech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technicien" }));
        jComboBox_FullNameTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FullNameTechActionPerformed(evt);
            }
        });

        jCheckBox_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ConfirmActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Activer:");

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));

        jTable_Alim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Montant par DHs", "Date", "Motif"
            }
        ));
        jScrollPane3.setViewportView(jTable_Alim);

        jTextField_Motif.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextField_Motif.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_Motif.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Motif.setText("Motif");
        jTextField_Motif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_MotifMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Details D'alimentation");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("AcoFrais");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Total frais:");

        jTextField_TotalFrais.setEditable(false);
        jTextField_TotalFrais.setBackground(new java.awt.Color(255, 248, 153));

        jButton_Solder.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton_Solder.setForeground(new java.awt.Color(102, 102, 102));
        jButton_Solder.setText("Solder");
        jButton_Solder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SolderActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Le nouveau solde du mois:");

        jTextField_NewSold.setEditable(false);
        jTextField_NewSold.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_NewSold.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTextField_NewSold.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_NewSold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_NewSold.setText("0.0");
        jTextField_NewSold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NewSoldMouseClicked(evt);
            }
        });
        jTextField_NewSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NewSoldActionPerformed(evt);
            }
        });

        jLabel_Date.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel_Date.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_Bonjours.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel_Bonjours.setForeground(new java.awt.Color(255, 51, 0));

        jButton_ValiderDeplacement.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_ValiderDeplacement.setForeground(new java.awt.Color(102, 102, 102));
        jButton_ValiderDeplacement.setText("Valider le deplacement");
        jButton_ValiderDeplacement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValiderDeplacementActionPerformed(evt);
            }
        });

        jButton_AddToSoldNow.setMnemonic('H');
        jButton_AddToSoldNow.setText("jButton1");
        jButton_AddToSoldNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AddToSoldNowMouseClicked(evt);
            }
        });
        jButton_AddToSoldNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddToSoldNowActionPerformed(evt);
            }
        });
        jButton_AddToSoldNow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_AddToSoldNowKeyPressed(evt);
            }
        });

        jCheckBox_Calculate.setSelected(true);
        jCheckBox_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CalculateActionPerformed(evt);
            }
        });

        jButton_SupprimerLigne.setBackground(new java.awt.Color(255, 255, 255));
        jButton_SupprimerLigne.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        jButton_SupprimerLigne.setForeground(new java.awt.Color(255, 0, 0));
        jButton_SupprimerLigne.setText("Supprimer une ligne");
        jButton_SupprimerLigne.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_SupprimerLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SupprimerLigneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total Frais:");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Differance:");

        jLabel_TotalFrais.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_TotalFrais.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel_TotalFrais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TotalFrais.setText("0.0");
        jLabel_TotalFrais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_TotalFrais.setOpaque(true);

        jLabel_Differance.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Differance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Differance.setForeground(new java.awt.Color(204, 0, 51));
        jLabel_Differance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Differance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Differance.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter un client");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox_Client.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jComboBox_Client.setForeground(new java.awt.Color(204, 0, 0));
        jComboBox_Client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner un client" }));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Statistiques");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_Refrech.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton_Refrech.setForeground(new java.awt.Color(153, 153, 153));
        jButton_Refrech.setText("Actualiser la table");
        jButton_Refrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefrechActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Sortir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jCheckBox_Confirm))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_FullNameTech, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_TotalFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_TotalFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Solder, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton_Refrech, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_NewSold, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Differance, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_LastMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton_AddToSoldNow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(153, 153, 153)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_AlimSold, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_Alim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Motif, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Valider))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField_SoldNow, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_Calculate)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel_Bonjours, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(217, 217, 217)
                        .addComponent(jLabel10)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel11)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_SupprimerLigne, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jComboBox_Client, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser_DateInt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_Frais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jButton_ValiderDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_LastMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton_AddToSoldNow))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_AlimSold, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateChooser_Alim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Motif, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SoldNow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jCheckBox_Calculate))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Bonjours, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_DateInt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField_Frais, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ValiderDeplacement))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_FullName))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jButton_SupprimerLigne))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel14)
                                .addGap(3, 3, 3)
                                .addComponent(jCheckBox_Confirm))
                            .addComponent(jLabel_TotalFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_NewSold, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_Differance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Refrech)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TotalFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_FullNameTech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Solder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String alimDate;
    private void jButton_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValiderActionPerformed
         Double value1 = 0.0;
         Double alimSold = 0.0;
        String motif = jTextField_Motif.getText();
        if(!jTextField_AlimSold.getText().equals(""))
        {
          alimSold = Double.valueOf(jTextField_AlimSold.getText());
        }
        //String alimDate = jDateChooser_Alim.getDate() ;
        //Double newAlim;
        if(alim.verifyTextPart1())
        {
            String pattern = "yyyy-MM-dd";
        SimpleDateFormat dateFormat = new SimpleDateFormat(pattern);        
         alimDate = dateFormat.format(jDateChooser_Alim.getDate());
        
        alim.alim(alimSold, alimDate, motif);
        jTable_Alim.setModel(new DefaultTableModel(null, new Object[]{"Montant par DHs", "Date", "Motif"}));
        alim.fillTableAlim(jTable_Alim);
        
        //the solution for new sold hopfully
          Double lastAlim = Double.valueOf(jTextField_AlimSold.getText());
          Double newSold = Double.valueOf(jTextField_NewSold.getText());
          Double allNewSold = lastAlim + newSold;
          jTextField_NewSold.setText(String.valueOf(allNewSold));
          
          Double nowSold = Double.valueOf(jTextField_SoldNow.getText());
          Double allNowSold = lastAlim + nowSold;
          jTextField_SoldNow.setText(String.valueOf(allNowSold));
          
        //empty all the fields
        jTextField_AlimSold.setText("");
        jDateChooser_Alim.setDate(null);
        jTextField_Motif.setText("");
      
        
        
        // getting the new sold after calculation and use it iin deleteinsertmoneyleft method
        // to bring the new sold to field jtextfield_newsold
        Double now = Double.valueOf(jTextField_NewSold.getText());
            alim.deleteInsertMoneyLeft(alimDate, now);
            alim.MoneyLeft();
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
            
        
        }
    }//GEN-LAST:event_jButton_ValiderActionPerformed

    private void jButton_ValiderDeplacementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValiderDeplacementActionPerformed
        
    if(!jComboBox_Client.getSelectedItem().equals("Sélectionner un client")){
       if(alim.verifyTextPart2())
       {
            //String client = jTextField_Client.getText();
            String client = jComboBox_Client.getSelectedItem().toString();
            String interventionMotif = jTextArea_MotifInt.getText();
            Double frais = Double.valueOf(jTextField_Frais.getText());
            String selectedItem = String.valueOf(jComboBox_FullName.getSelectedItem());
            int spaceIndex = selectedItem.indexOf(" ");
            String nom = selectedItem.substring(0, spaceIndex);
        
            int userId = alim.returnUserId(nom);
            String patern = "yyyy-MM-dd";
            SimpleDateFormat dateFormat = new SimpleDateFormat(patern);
            String interventionDate = dateFormat.format(jDateChooser_DateInt.getDate());
            alim.intervention(userId, client, interventionDate, frais, interventionMotif);
            jTable_Frais.setModel(new DefaultTableModel(null, new Object[]{"ID","Nom de Technicien",
                "Nom de Client", "Date D'intervention", "Frais de Deplacement", "Motif de Deplacement"}));
            alim.fillTableFrais(jTable_Frais);
            
            //put the money totalin a jLable_TotalFrais to be displayed whene adding a frais
            jLabel_TotalFrais.setText(String.valueOf(alim.totalFrais()));
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
            
           // empty all fields
            
            jDateChooser_DateInt.setDate(null);
            jTextField_Frais.setText("");
            jTextArea_MotifInt.setText("");
       }
    }
        else
        {
            JOptionPane.showMessageDialog(null, "Merci de Sélectionner un client");
        }
    }//GEN-LAST:event_jButton_ValiderDeplacementActionPerformed

    private void jTextField_MotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_MotifMouseClicked
        jTextField_Motif.setText("");
    }//GEN-LAST:event_jTextField_MotifMouseClicked

    private void jCheckBox_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ConfirmActionPerformed
        if(jCheckBox_Confirm.isSelected()){
        jComboBox_FullNameTech.setEnabled(true);
          jTextField_TotalFrais.setEnabled(true);
          jButton_Solder.setEnabled(true);
        }
        else
        {
          jComboBox_FullNameTech.setEnabled(false);
          jTextField_TotalFrais.setEnabled(false);
          jButton_Solder.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox_ConfirmActionPerformed
       int id_technician;
    private void jComboBox_FullNameTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FullNameTechActionPerformed
        String fullName = jComboBox_FullNameTech.getSelectedItem().toString();
        int spaceIndex = fullName.indexOf(" ");
            String nom = fullName.substring(0, spaceIndex);
            String prenom = fullName.substring(spaceIndex + 1);
            id_technician = alim.returnTechnicianId(nom, prenom);
            jTextField_TotalFrais.setText(String.valueOf(alim.amountToBeGiven(id_technician)));
            
            
        
    }//GEN-LAST:event_jComboBox_FullNameTechActionPerformed

    private void jButton_SolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SolderActionPerformed
        if(!jTextField_TotalFrais.getText().equals(""))                          // if technician is selected, go a head and calculate
        {
        int techId = id_technician;
        alim.convertStatusToOne(techId);
        jTable_Frais.setModel(new DefaultTableModel(null, new Object[]{"ID", "Nom de Technicien",
                "Nom de Client", "Date D'intervention", "Frais de Deplacement", "Motif de Deplacement"}));
            alim.fillTableFrais(jTable_Frais);
            
            //what next is puting the result of alimenttion substruct by technician sold and will be put in the this month fild
            Double now = alim.moneyLeft();
            Double tech = Double.valueOf(jTextField_TotalFrais.getText());
            
            Double total = now - tech;
            alim.deleteInsertMoneyLeft(alimDate, total);
            jTextField_NewSold.setText(String.valueOf(total));
            
            //Empty all fields after finish
            jComboBox_FullNameTech.setSelectedItem("");
            jTextField_TotalFrais.setText("");
            
            // disable all fields
            jComboBox_FullNameTech.setEnabled(false);
            jTextField_TotalFrais.setEnabled(false);
            jButton_Solder.setEnabled(false);
            jCheckBox_Confirm.setSelected(false);
            
            //put the money total in a jLable_TotalFrais to be displayed at solder
            jLabel_TotalFrais.setText(String.valueOf(alim.totalFrais()));
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
            
        }   
        else // if the money field is emty, send a message
        {
            JOptionPane.showMessageDialog(null, "Voulez-vous s'il vous plaît choisir un techhnicien d'abord!");
        }  
    }//GEN-LAST:event_jButton_SolderActionPerformed

    private void jTextField_NewSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NewSoldActionPerformed
        
    }//GEN-LAST:event_jTextField_NewSoldActionPerformed

    private void jTextField_NewSoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NewSoldMouseClicked
        //alim.MoneyLeft();
    }//GEN-LAST:event_jTextField_NewSoldMouseClicked

    private void jButton_AddToSoldNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddToSoldNowActionPerformed
           alim.lastMonthMoney();
           jTextField_SoldNow.setText(jTextField_LastMonth.getText());
           jTextField_NewSold.setText(String.valueOf(alim.moneyLeft()));
           alim.grabLastMonthMoney();
           jButton_AddToSoldNow.setEnabled(false);
              
                  
              
             
    }//GEN-LAST:event_jButton_AddToSoldNowActionPerformed

    private void jCheckBox_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CalculateActionPerformed
        if(jCheckBox_Calculate.isSelected())
        {
            Double lastMonth = Double.valueOf(jTextField_LastMonth.getText());
            Double soldNow = Double.valueOf(jTextField_SoldNow.getText());
            Double zammel = lastMonth + soldNow;
            
            jTextField_SoldNow.setText(String.valueOf(zammel));
        }
        else
        {
            Double lastMonth = Double.valueOf(jTextField_LastMonth.getText());
            Double soldNow = Double.valueOf(jTextField_SoldNow.getText());
            Double zammel =  soldNow - lastMonth ;
            
            jTextField_SoldNow.setText(String.valueOf(zammel));
        }
    }//GEN-LAST:event_jCheckBox_CalculateActionPerformed

    private void jButton_AddToSoldNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddToSoldNowMouseClicked
        
    }//GEN-LAST:event_jButton_AddToSoldNowMouseClicked

    private void jButton_AddToSoldNowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_AddToSoldNowKeyPressed
                
    }//GEN-LAST:event_jButton_AddToSoldNowKeyPressed

    private void jTextField_LastMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LastMonthMouseClicked
        if(evt.getClickCount() == 3)
        {
            jButton_AddToSoldNow.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField_LastMonthMouseClicked
      int index;
    private void jButton_SupprimerLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SupprimerLigneActionPerformed
       if(!jTable_Frais.getSelectionModel().isSelectionEmpty())
       {
        String rowId = jTable_Frais.getValueAt(index,0).toString();
        int id = Integer.valueOf(rowId);
        int yesOrNo = JOptionPane.showConfirmDialog(null, "étes-vous certain de vouloir supprimer cette ligne?",
                        "Supprission", JOptionPane.OK_CANCEL_OPTION);
            if(yesOrNo == 0)
            {
            alim.delteteRowFrais(id);
            jTable_Frais.setModel(new DefaultTableModel(null, new Object[]{"ID","Nom de Technicien",
                "Nom de Client", "Date D'intervention", "Frais de Deplacement", "Motif de Deplacement"}));
            alim.fillTableFrais(jTable_Frais);
            
            //put the money totalin a jLable_TotalFrais to be displayed whene adding a frais
            jLabel_TotalFrais.setText(String.valueOf(alim.totalFrais()));
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
            }
       }
       else
       {
           JOptionPane.showMessageDialog(null, "D'abord, vous devez sélectionner une ligne à supprimer");
       }

        
       
    }//GEN-LAST:event_jButton_SupprimerLigneActionPerformed

    private void jTable_FraisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_FraisMouseClicked
            index = jTable_Frais.getSelectedRow();            
            System.out.println(index);
    }//GEN-LAST:event_jTable_FraisMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddClientForm acf = new AddClientForm();
        acf.pack();
        acf.setVisible(true);
        acf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        acf.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StatForm stat = new StatForm();
        stat.pack();
        stat.setVisible(true);
        stat.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        stat.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_RefrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefrechActionPerformed
        jTable_Frais.setModel(new DefaultTableModel(null, new Object[]{"ID","Nom de Technicien",
                "Nom de Client", "Date D'intervention", "Frais de Deplacement", "Motif de Deplacement"}));
            alim.fillTableFrais(jTable_Frais);
            
            //put the money totalin a jLable_TotalFrais to be displayed whene adding a frais
            jLabel_TotalFrais.setText(String.valueOf(alim.totalFrais()));
            
            // the diffrence between sold and frais in a jLable_Diffrence
            Double actualSold = Double.valueOf(jTextField_NewSold.getText());
            Double totalFrais = Double.valueOf(jLabel_TotalFrais.getText());
            Double diffrence = actualSold - totalFrais;
            jLabel_Differance.setText(String.valueOf(diffrence));
    }//GEN-LAST:event_jButton_RefrechActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_AlimSoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_AlimSoldMouseClicked
        jTextField_AlimSold.setText("");
    }//GEN-LAST:event_jTextField_AlimSoldMouseClicked

    private void jTextField_AlimSoldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AlimSoldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AlimSoldKeyTyped

    private void jTextField_FraisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FraisKeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_FraisKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcoSold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AcoSold().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton_AddToSoldNow;
    private javax.swing.JButton jButton_Refrech;
    private javax.swing.JButton jButton_Solder;
    private javax.swing.JButton jButton_SupprimerLigne;
    private javax.swing.JButton jButton_Valider;
    private javax.swing.JButton jButton_ValiderDeplacement;
    private javax.swing.JCheckBox jCheckBox_Calculate;
    private javax.swing.JCheckBox jCheckBox_Confirm;
    public static javax.swing.JComboBox<String> jComboBox_Client;
    public static javax.swing.JComboBox<String> jComboBox_FullName;
    public static javax.swing.JComboBox<String> jComboBox_FullNameTech;
    public static com.toedter.calendar.JDateChooser jDateChooser_Alim;
    public static com.toedter.calendar.JDateChooser jDateChooser_DateInt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel_Bonjours;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Differance;
    private javax.swing.JLabel jLabel_TotalFrais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTable jTable_Alim;
    private javax.swing.JTable jTable_Frais;
    public static javax.swing.JTextArea jTextArea_MotifInt;
    public static javax.swing.JTextField jTextField_AlimSold;
    public static javax.swing.JTextField jTextField_Frais;
    public static javax.swing.JTextField jTextField_LastMonth;
    public static javax.swing.JTextField jTextField_Motif;
    public static javax.swing.JTextField jTextField_NewSold;
    private javax.swing.JTextField jTextField_SoldNow;
    private javax.swing.JTextField jTextField_TotalFrais;
    // End of variables declaration//GEN-END:variables
}


/*

String sn = jTextField_SoldNow.getText();
        Double csn = Double.valueOf(sn);
        Double ta = alim.totalAlim();
        Double totalCsnAndTa = csn + ta;
        jTextField_SoldNow.setText(String.valueOf(totalCsnAndTa));//alim.totalAlim()

*/
