/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acosold;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Radouan
 */
public class StatForm extends javax.swing.JFrame {

    /**
     * Creates new form StatForm
     * 
     */
    Statistics stat = new Statistics();
    Alimentation alim = new Alimentation();
//    Client clt = new Client();
    public StatForm() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("acoLogo.jpg")).getImage());
        // fill the combobox with technicians full names and other combobox with clients names
        stat.fillComboBoxTechnicianStats();
        stat.fillClientComboBoxStats();
        Date d = new Date();
        jDateChooser_From.setDate(d);
        jDateChooser_End.setDate(d);
        jDateChooser_FromFrais.setDate(d);
        jDateChooser_EndFrais.setDate(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Stats = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser_From = new com.toedter.calendar.JDateChooser();
        jDateChooser_End = new com.toedter.calendar.JDateChooser();
        jButton_OkAlim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_TotalAlim = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jDateChooser_FromFrais = new com.toedter.calendar.JDateChooser();
        jDateChooser_EndFrais = new com.toedter.calendar.JDateChooser();
        jButton_OkFrais = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_StatsFrais = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Client = new javax.swing.JComboBox<>();
        jComboBox_Technicien = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel_TotalFraisTechnicien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Sortir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcoSold v1.3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable_Stats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alimentation", "Date", "Motif"
            }
        ));
        jScrollPane1.setViewportView(jTable_Stats);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("La partie de statistique : ALIMENTATION");

        jDateChooser_From.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser_From.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jDateChooser_End.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser_End.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton_OkAlim.setBackground(new java.awt.Color(255, 255, 255));
        jButton_OkAlim.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton_OkAlim.setForeground(new java.awt.Color(255, 102, 0));
        jButton_OkAlim.setText("OK");
        jButton_OkAlim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkAlimActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Total alimentations:");

        jLabel_TotalAlim.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        jLabel_TotalAlim.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_TotalAlim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TotalAlim.setToolTipText("");
        jLabel_TotalAlim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("La partie de statistique : FRAIS");

        jDateChooser_FromFrais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser_FromFrais.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jDateChooser_EndFrais.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser_EndFrais.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButton_OkFrais.setBackground(new java.awt.Color(255, 255, 255));
        jButton_OkFrais.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton_OkFrais.setForeground(new java.awt.Color(255, 102, 0));
        jButton_OkFrais.setText("OK");
        jButton_OkFrais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkFraisActionPerformed(evt);
            }
        });

        jTable_StatsFrais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Client", "Date", "Frais", "Motif"
            }
        ));
        jScrollPane2.setViewportView(jTable_StatsFrais);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("DHs");

        jComboBox_Client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client" }));
        jComboBox_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClientActionPerformed(evt);
            }
        });

        jComboBox_Technicien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technicien" }));
        jComboBox_Technicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TechnicienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Total frais:");

        jLabel_TotalFraisTechnicien.setFont(new java.awt.Font("Times New Roman", 1, 42)); // NOI18N
        jLabel_TotalFraisTechnicien.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_TotalFraisTechnicien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TotalFraisTechnicien.setToolTipText("");
        jLabel_TotalFraisTechnicien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("DHs");

        jButton_Sortir.setText("Sortir");
        jButton_Sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 490, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser_End, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_OkAlim, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_TotalAlim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_OkFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser_FromFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_EndFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox_Technicien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_Sortir)
                .addGap(397, 397, 397)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_TotalFraisTechnicien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_OkAlim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser_End, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                            .addComponent(jDateChooser_From, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TotalAlim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jDateChooser_FromFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser_EndFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton_OkFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Technicien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_TotalFraisTechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Sortir))
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OkAlimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkAlimActionPerformed
            String patern = "yyyy-MM-dd";
            SimpleDateFormat dateFormat = new SimpleDateFormat(patern);
            String beginingDate = dateFormat.format(jDateChooser_From.getDate());
            String endDate = dateFormat.format(jDateChooser_End.getDate());
            jTable_Stats.setModel(new DefaultTableModel(null, new Object[]{"Alimentation",
                "Date", "Motif"}));
            if(stat.isAlimTableEmpty(beginingDate, endDate))
            {
            stat.returnAPeriod(jTable_Stats, beginingDate, endDate);
            jLabel_TotalAlim.setText(String.valueOf(stat.totalAlimDateAlim(beginingDate, endDate)));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Il n'y a pas d'enregistrements!");
                jLabel_TotalAlim.setText("");
            }
    }//GEN-LAST:event_jButton_OkAlimActionPerformed

    private void jButton_OkFraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkFraisActionPerformed
            String patern = "yyyy-MM-dd";
            SimpleDateFormat dateFormat = new SimpleDateFormat(patern);
            String beginingDate = dateFormat.format(jDateChooser_FromFrais.getDate());
            String endDate = dateFormat.format(jDateChooser_EndFrais.getDate());
            jTable_StatsFrais.setModel(new DefaultTableModel(null, new Object[]{"Nom",
                "Prenom", "Client", "Date","Frais", "Motif"}));
//        if(beginingDate != null && endDate != null)
//        {
            if(stat.isFraisTableEmpty(beginingDate, endDate))
            {
            stat.returnAPeriodFrais(jTable_StatsFrais, beginingDate, endDate);
             jLabel_TotalFraisTechnicien.setText(String.valueOf(stat.totalAlimDate(beginingDate, endDate)));
            //jLabel_TotalAlim.setText(String.valueOf(alim.totalAlim()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Il n'y a pas d'enregistrements!");
                jLabel_TotalFraisTechnicien.setText("");
            }
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Choisissez d'abord une période!");
//        }
    }//GEN-LAST:event_jButton_OkFraisActionPerformed

    private void jComboBox_TechnicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TechnicienActionPerformed
       // condition of combobox, does it equal to technicien, if yes, send a messange else execute
            String patern = "yyyy-MM-dd";
            SimpleDateFormat dateFormat = new SimpleDateFormat(patern);
            String beginingDate = dateFormat.format(jDateChooser_FromFrais.getDate());
            String endDate = dateFormat.format(jDateChooser_EndFrais.getDate());
//if(beginingDate != null && endDate != null)
//    {
        if(!jComboBox_Technicien.getSelectedItem().toString().equals("Technicien"))    
        {
        String fullName = jComboBox_Technicien.getSelectedItem().toString();
        int endChar = fullName.indexOf(" ");
        String nom = fullName.substring(0, endChar);
        String prenom = fullName.substring(endChar + 1);
        // erase the table from all the data befor make it full again
        jTable_StatsFrais.setModel(new DefaultTableModel(null, new Object[]{"Nom",
                "Prenom", "Client", "Date","Frais", "Motif"}));
        
        // if the query bring data back, execute,else send a message
        if(stat.isFraisTableEmptyFullName(nom, prenom, beginingDate, endDate))
        {
            stat.fillTableWithSpesificTechnicien(jTable_StatsFrais, nom, prenom, beginingDate, endDate);
            jLabel_TotalFraisTechnicien.setText(String.valueOf(stat.totalAlimTechnicien(nom, prenom, beginingDate, endDate)));
        }//end of second if condition
        else
        {
            JOptionPane.showMessageDialog(null, "Il n'y a pas d'enregistrements pour: " + fullName);
        }
        }// end of the first ifcondition
        else
        {
            JOptionPane.showMessageDialog(null,"Sélectionner un technicien");
        }
        
//    }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Choisissez d'abord une période!");
//        }
        
        
    }//GEN-LAST:event_jComboBox_TechnicienActionPerformed

    private void jComboBox_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClientActionPerformed
        
            String patern = "yyyy-MM-dd";
            SimpleDateFormat dateFormat = new SimpleDateFormat(patern);
            String beginingDate = dateFormat.format(jDateChooser_FromFrais.getDate());
            String endDate = dateFormat.format(jDateChooser_EndFrais.getDate());
        String client = jComboBox_Client.getSelectedItem().toString();
        jTable_StatsFrais.setModel(new DefaultTableModel(null, new Object[]{"Nom",
                "Prenom", "Client", "Date","Frais", "Motif"}));
        if(!client.equals("Client")){
        if(stat.isFraisTableEmptyClient(client, beginingDate, endDate))
        {
        stat.fillTableWithSpesificClient(jTable_StatsFrais, client, beginingDate, endDate);
        jLabel_TotalFraisTechnicien.setText(String.valueOf(stat.totalAlimClient(client, beginingDate, endDate)));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Il n'y a pas d'enregistrements pour: " + client);
        }
            
//        System.out.println(client);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sélectionner un Client");
        }
    }//GEN-LAST:event_jComboBox_ClientActionPerformed

    private void jButton_SortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SortirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_SortirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StatForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_OkAlim;
    private javax.swing.JButton jButton_OkFrais;
    private javax.swing.JButton jButton_Sortir;
    public static javax.swing.JComboBox<String> jComboBox_Client;
    public static javax.swing.JComboBox<String> jComboBox_Technicien;
    private com.toedter.calendar.JDateChooser jDateChooser_End;
    private com.toedter.calendar.JDateChooser jDateChooser_EndFrais;
    private com.toedter.calendar.JDateChooser jDateChooser_From;
    private com.toedter.calendar.JDateChooser jDateChooser_FromFrais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_TotalAlim;
    private javax.swing.JLabel jLabel_TotalFraisTechnicien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTable_Stats;
    public static javax.swing.JTable jTable_StatsFrais;
    // End of variables declaration//GEN-END:variables
}
